// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKtmwQCA0OLom4dnDaGO5Z6Wow5s_0BRE',
    appId: '1:56725496828:web:a6e8da7117bbefef354879',
    messagingSenderId: '56725496828',
    projectId: 'online-hospital-b4584',
    authDomain: 'online-hospital-b4584.firebaseapp.com',
    storageBucket: 'online-hospital-b4584.firebasestorage.app',
    measurementId: 'G-HBS41T2FXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF-ItETAmYdbeLj2UwfD1pvkQzT87q-IU',
    appId: '1:56725496828:android:c8c2e5f6e94bcb0c354879',
    messagingSenderId: '56725496828',
    projectId: 'online-hospital-b4584',
    storageBucket: 'online-hospital-b4584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjzw3C8iZ_cdcZWRAArSnuJdgXw9VXQOM',
    appId: '1:56725496828:ios:1c3ea68e828e2a75354879',
    messagingSenderId: '56725496828',
    projectId: 'online-hospital-b4584',
    storageBucket: 'online-hospital-b4584.firebasestorage.app',
    androidClientId: '56725496828-7a9vpunha2mrnccbhlc27com4b486koq.apps.googleusercontent.com',
    iosClientId: '56725496828-ti5kivlsijasgq96d8t8o7ffmqiidmd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.online',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjzw3C8iZ_cdcZWRAArSnuJdgXw9VXQOM',
    appId: '1:56725496828:ios:1c3ea68e828e2a75354879',
    messagingSenderId: '56725496828',
    projectId: 'online-hospital-b4584',
    storageBucket: 'online-hospital-b4584.firebasestorage.app',
    androidClientId: '56725496828-7a9vpunha2mrnccbhlc27com4b486koq.apps.googleusercontent.com',
    iosClientId: '56725496828-ti5kivlsijasgq96d8t8o7ffmqiidmd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.online',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKtmwQCA0OLom4dnDaGO5Z6Wow5s_0BRE',
    appId: '1:56725496828:web:0f11cd1da67dbd5e354879',
    messagingSenderId: '56725496828',
    projectId: 'online-hospital-b4584',
    authDomain: 'online-hospital-b4584.firebaseapp.com',
    storageBucket: 'online-hospital-b4584.firebasestorage.app',
    measurementId: 'G-TVW1D6C0BZ',
  );
}
